### ISSUE TITLE
Add EverlastingBugstopper and drager as maintainers

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rustwasm/binary-install#12]
Would love 

- [ ] cargo publish permissions
- [x] repo permissions

ofc open for discussion and buy-in from rustwasm folks and @ashleygwilliams 

cc @drager

**Comment by ashleygwilliams** [comment]
i'm a fan. let me know what you think @drager and i can make the additions!

**Comment by drager** [comment]
Sounds good to me! 🙂
