### ISSUE TITLE
Release to crates.io?

### ISSUE THREAD

**Issue by printfn** [rustwasm/binary-install#22]
Hi, now that https://github.com/rustwasm/binary-install/pull/21 has been merged, would it be possible to get a new release published on crates.io? This is needed for wasm-pack to be able to use the new version, in https://github.com/rustwasm/wasm-pack/pull/1188.

**Comment by drager** [comment]
Sorry for the late response. Published in [0.1.0](https://crates.io/crates/binary-install/0.1.0)
