### ISSUE TITLE
Stabilize 0.0.3

### ISSUE THREAD

**Issue by EverlastingBugstopper** [rustwasm/binary-install#8]
The current release has been "alpha" for quite a while - I'm not quite sure what has to happen to stabilize, but I'm very happy to help!

**Comment by ashleygwilliams** [comment]
yeah, we're in an alpha because i was extremely not confident in the general viability of very rapid changes i needed to make to get @cloudflare/wrangler out the door, and did not want to affect @rustwasm/wasm-pack. 

i can take on cleaning that up! thanks for the poke
